WinCmd/Models/Command.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WinCmd.Models
{
    public class Command
    {
    }
}

WinCmd/Models/ErrorViewModel.cs
using System;

namespace WinCmd.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WinCmd/Models/Event.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WinCmd.Models
{
    public class Event
    {
        public int Id { get; set; }
        public string Source { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    }
}

WinCmd/Models/Link.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WinCmd.Models
{
    public class Link
    {
        public int Id { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
    }
}

WinCmd/Models/News.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WinCmd.Models
{
    public class News
    {
    }
}

WinCmd/Models/Utility.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WinCmd.Models
{
    public class Utility
    {
    }
}

WinCmd/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WinCmd.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WinCmd/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WinCmd.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WinCmd/Controllers/CommandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WinCmd.Controllers
{
    public class CommandsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WinCmd/Controllers/DevIntelligenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WinCmd.Controllers
{
    public class DevIntelligenceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WinCmd/Controllers/DevlangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WinCmd.Controllers
{
    public class DevLangController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WinCmd/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WinCmd.Controllers
{
    public class EventsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WinCmd/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WinCmd.Models;

namespace WinCmd.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult About() => View();

        public IActionResult Contact() => View();

        public IActionResult News() => View();

        public IActionResult Links() => View();
    }
}

WinCmd/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WinCmd.Controllers
{
    public class NewsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WinCmd/Controllers/UtilityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WinCmd.Controllers
{
    public class UtilityController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WinCmd/Views/Commands/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

WinCmd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WinCmd</title>

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/css/base.css" />
    <link rel="stylesheet" type="text/css" href="~/css/header.css" />
    <link rel="stylesheet" type="text/css" href="~/css/content.css" />
    <link rel="stylesheet" type="text/css" href="~/css/footer.css" />
</head>
<body>
    <header>        
        <nav id="mainMenu">
            <ul>
                <li><a asp-controller="Home" asp-action="Index">Main</a></li>
                <li><a asp-controller="News" asp-action="Index">News</a></li>
                <li><a asp-controller="Commands" asp-action="Index">Commands</a></li>
                <li><a asp-controller="Utility" asp-action="Index">Utility</a></li>
                <li><a asp-controller="Scripts" asp-action="Index">Scripts</a></li>
                <li><a asp-controller="Home" asp-action="Links">Links</a></li>
            </ul>            
        </nav>
    </header>
    <div id="content">
            @RenderBody()
    </div>

    <footer>
        <div id="footerInner">
            <div id="icons">
                <img src="images/facebook.png" alt="FB"></img>
                <img src="images/twitter.png" alt="TW"></img>
                <img src="images/linkedin.png" alt="LinkedIn"></img>
                <img src="images/youtube.png" alt="YouTube"></img>
            </div>
            <div id="footerMenu">
                <div class="footeritem">Карта сайта</div>                
            </div>
            <div id="copyright">
                <div id="company">Copyright 2019</div>                
            </div>
        </div>
    </footer>   

    @RenderSection("Scripts", required: false)
</body>
</html>