City/CityWeb/Models/ErrorViewModel.cs
using System;

namespace CityWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

City/CityWeb/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CityWeb.Domain.Abstract;
using CityWeb.Domain.Entities;

namespace CityWeb.Controllers
{
    public class CityController : Controller
    {
        private ICityRepository repo;

        public CityController(ICityRepository repository)
        {
            repo = repository;
        }

        public IActionResult List(int cityid)
        {
            IEnumerable<City> cities = repo.Cities
                .Where(c => c.Id == cityid);

            return View(cities);
        }
    }
}

City/CityWeb/Controllers/ContinentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CityWeb.Domain.Abstract;
using CityWeb.Domain.Entities;

namespace CityWeb.Controllers
{
    public class ContinentController : Controller
    {
        private IContinentRepository repo;

        public ContinentController(IContinentRepository repository)
        {
            repo = repository;
        }

        public IActionResult List()
        {
            IEnumerable<Continent> continents = repo.Continents;

            return View(continents);
        }
    }
}

City/CityWeb/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CityWeb.Domain.Abstract;
using CityWeb.Domain.Entities;

namespace CityWeb.Controllers
{
    public class CountryController : Controller
    {
        private ICountryRepository repo;

        public CountryController(ICountryRepository repository)
        {
            repo = repository;
        }

        // GET: /<controller>/
        public IActionResult List(int continent)
        {
            ViewBag.WithHolidays = false;

            IEnumerable<Country> countries = repo.Countries
                .Where(c => c.Continent == continent);

            return View(countries);
        }

        public IActionResult Holidays(string countrycode)
        {
            Country c = repo.Countries
                .FirstOrDefault(x => x.Code == countrycode);

            if (c != null)
            {
                return View(c);
            }
            else return View();
        }

        public IActionResult Calendar(string calendarcode)
        {
            Country c = repo.Countries
                .FirstOrDefault(x => x.Code == calendarcode);

            if (c != null)
            {
                return View(c);
            }
            else return View();
        }
    }
}

City/CityWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CityWeb.Models;

namespace CityWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

City/CityWeb/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CityWeb.Domain.Abstract;
using CityWeb.Domain.Entities;

namespace CityWeb.Controllers
{
    public class NavController : Controller
    {
        private IContinentRepository repo;

        public NavController(IContinentRepository repository)
        {
            repo = repository;
        }

        // GET: Nav
        public PartialViewResult Menu(string continent = null)
        {
            ViewBag.SelectedContinent = continent;
            IEnumerable<Continent> continents = repo.Continents
                .OrderBy(x => x.Id);

            return PartialView(continents);
        }
    }
}

City/CityWeb/Views/City/List.cshtml
@model IEnumerable<CityWeb.Domain.Entities.City>
@{
    ViewData["Title"] = "List of cities";
}

<h3>Cities</h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="col">@item.Id</td>
                <td class="col">@Html.ActionLink(item.Name, string.Format("Holidays/{0}", item.Id))</td>
            </tr>
        }
    </tbody>
</table>

City/CityWeb/Views/Country/Calendar.cshtml
@model CityWeb.Domain.Entities.Country
@{
    ViewData["Title"] = "Calendar";
}

<h2>Calendar for @Model.Name</h2>
<div id="calendar"></div>

@section ScriptsCalendar{
    <script>
            $(function () {
                var holidays = '@Model.Holidays';

                console.log(holidays);

                if (holidays) {
                    var array_date = holidays.split(';');

                    var my_datasource = [];

                    array_date.forEach(function (item) {
                        var array_day = item.split('-');
                        var year = array_day[0];
                        var month = array_day[1] - 1;
                        var day = array_day[2];

                        var holidayDate = new Date(year, month, day);

                        my_datasource.push({ startDate: holidayDate, endDate: holidayDate, color: '#FF0000' });
                    });

                    var currentYear = new Date().getFullYear();

                    $('#calendar').calendar({
                        dataSource: my_datasource,
                        style: 'background'
                    });
                }
            });
    </script>
}

City/CityWeb/Views/Country/Holidays.cshtml
@model CityWeb.Domain.Entities.Country
@{
    ViewData["Title"] = "Holidays";
}

<h3>Country @Model.Name</h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Code</th>
            <th scope="col">Name</th>
            <th scope="col">Holidays</th>
            <th scope="col">Calendar</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="col">@Model.Code</td>
            <td class="col">@Model.Name</td>
            <td class="col">@Model.Holidays</td>
            <td class="col">@Html.ActionLink("...", string.Format("Calendar/{0}", Model.Code))</td>
        </tr>
    </tbody>
</table>

City/CityWeb/Views/Country/List.cshtml
@model IEnumerable<CityWeb.Domain.Entities.Country>
@{
    ViewData["Title"] = "List of countries";
}

<h3>Countries List</h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Code</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="col">@item.Code</td>
                <td class="col">@Html.ActionLink(item.Name, string.Format("Holidays/{0}", item.Code))</td>
            </tr>
        }
    </tbody>
</table>

City/CityWeb/Views/Nav/Menu.cshtml
@model IEnumerable<CityWeb.Domain.Entities.Continent>
@{
    ViewData["Title"] = "Menu";
}

@Html.ActionLink("Home", "List", "Continent")

@foreach (var item in Model)
{
    @Html.RouteLink(item.Name,
        new {
            controller = "Country",
            action = "List",
            continent = item.Id
        }
    )
}