Translate/TranslateCore/Models/Pronoun.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TranslateCore.Models
{
    public class Pronoun
    {
        [Key]
        public int Id { get; set; }
        public string PronounEng { get; set; }
        public string PronounRu { get; set; }
    }
}

Translate/TranslateCore/Controllers/PronounsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TranslateCore.Domain;
using TranslateCore.Models;

namespace TranslateCore.Controllers
{
    public class PronounsController : Controller
    {
        private TranslateDb db;

        public PronounsController(TranslateDb injectDb)
        {
            db = injectDb;
        }

        public IActionResult Index()
        {
            return View(db.Pronouns);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Pronoun pronoun)
        {
            if (ModelState.IsValid)
            {
                if (pronoun != null)
                {
                    var find_pronoun = db.Pronouns.FirstOrDefault(w => w.PronounEng == pronoun.PronounEng);
                    var find_word = db.Words.FirstOrDefault(w => w.WordEng == pronoun.PronounEng);

                    if (find_pronoun == null)
                    {
                        db.Pronouns.Add(pronoun);

                        var word = new Word()
                        {
                            WordEng = pronoun.PronounEng,
                            WordRu = pronoun.PronounRu
                        };
                        db.Words.Add(word);
                        db.SaveChanges();
                    }
                    else
                    {
                        find_pronoun.PronounRu = pronoun.PronounRu;
                        db.Pronouns.Update(find_pronoun);
                        db.SaveChanges();
                    }
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(pronoun);
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var find_pronoun = db.Pronouns.FirstOrDefault(w => w.Id == Convert.ToInt32(id));

            return View(find_pronoun);
        }

        [HttpPost]
        public IActionResult Edit(Pronoun pronoun)
        {
            if (ModelState.IsValid)
            {
                var find_pronoun = db.Pronouns.FirstOrDefault(w => w.Id == pronoun.Id);

                if (find_pronoun != null)
                {
                    find_pronoun.PronounEng = pronoun.PronounEng;
                    find_pronoun.PronounRu = pronoun.PronounRu;
                    db.Pronouns.Update(find_pronoun);
                    db.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pronoun);
        }

        public IActionResult Delete(string id)
        {
            var find_pronoun = db.Pronouns.FirstOrDefault(w => w.Id == Convert.ToInt32(id));

            if (find_pronoun != null)
            {
                db.Pronouns.Remove(find_pronoun);
                db.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Translate/TranslateCore/Views/Pronouns/Create.cshtml
@model Pronoun
@{
    ViewData["Title"] = "Create";
}

<h2>Create Pronoun</h2>
<div class="row">
    <div class="col-md-3">
        <form asp-action="Create" asp-controller="Pronouns" method="post">
            <div class="form-group">
                <label asp-for="PronounEng"></label>
                <input asp-for="PronounEng" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PronounRu"></label>
                <input asp-for="PronounRu" class="form-control" />
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
            <a asp-action="Index" class="btn btn-default">Cancel</a>
        </form>
    </div>
</div>

Translate/TranslateCore/Views/Pronouns/Edit.cshtml
@model Pronoun
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Word</h2>
<div class="row">
    <div class="col-md-3">
        <form asp-action="Edit" asp-controller="Pronouns" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PronounEng"></label>
                <input asp-for="PronounEng" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PronounRu"></label>
                <input asp-for="PronounRu" class="form-control" />
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
            <a asp-action="Index" class="btn btn-default">Cancel</a>
        </form>
    </div>
</div>

Translate/TranslateCore/Views/Pronouns/Index.cshtml
@model IEnumerable<Pronoun>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col">
        <div class="caption">
            <h2>Pronouns</h2>

            <a class="btn btn-primary" asp-action="Create" asp-controller="Pronouns">Create word</a>
        </div>        
        <table id="dictionary" class="table table-striped">
            <tr><th>Id</th><th>English</th><th>Russia</th><th></th></tr>
            @if (Model.Count() == 0)
            {
                <tr><td colspan="3" class="text-center">No words</td></tr>
            }
            else
            {
                @foreach (var pronoun in Model)
                {
                    <tr>
                        <td>@pronoun.Id</td>
                        <td>@pronoun.PronounEng</td>
                        <td>@pronoun.PronounRu</td>
                        <td>
                            <form asp-controller="Pronouns" asp-action="Delete" asp-route-id="@pronoun.Id" method="post">
                                <a class="btn btn-sm btn-primary" asp-controller="Pronouns" asp-action="Edit" asp-route-id="@pronoun.Id">Edit</a>
                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</div>
<script src="~/js/translate.js"></script>