Translate/TranslateCore/Models/WordCategory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace TranslateCore.Models
{
    public class WordCategory
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameRu { get; set; }        
    }
}

Translate/TranslateCore/Controllers/WordCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TranslateCore.Domain;
using TranslateCore.Models;

namespace TranslateCore.Controllers
{
    public class WordCategoryController : Controller
    {
        private TranslateDb db;

        public WordCategoryController(TranslateDb injectDb)
        {
            db = injectDb;
        }

        public IActionResult Index(string filter = "all")
        {
            if (filter != "all")
            {
                return View(db.WordCategories                      
                    .Where(w => w.Name.StartsWith(filter))                    
                    .OrderBy(w=> w.Name)
                    );
            }
            return View(db.WordCategories.OrderBy(w => w.Name));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(WordCategory wordCategory)
        {
            if (ModelState.IsValid)
            {                
                var find_verb = db.WordCategories.FirstOrDefault(w => w.Name == wordCategory.Name);                    

                if (find_verb == null)
                {                    
                    db.WordCategories.Add(wordCategory);                        
                    db.SaveChanges();
                }                    
                return RedirectToAction(nameof(Index));                
            }
            return View(wordCategory);
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var find_word = db.WordCategories.FirstOrDefault(w => w.Id == Convert.ToInt32(id));

            return View(find_word);
        }

        [HttpPost]
        public IActionResult Edit(WordCategory wordCategory)
        {
            if (ModelState.IsValid)
            {
                db.WordCategories.Update(wordCategory);
                db.SaveChanges();                
                return RedirectToAction(nameof(Index));
            }
            return View(wordCategory);
        }

        public IActionResult Delete(string id)
        {
            var find_word = db.WordCategories.FirstOrDefault(w => w.Id == Convert.ToInt32(id));

            if (find_word != null)
            {
                db.WordCategories.Remove(find_word);
                db.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Translate/TranslateCore/Views/WordCategory/Create.cshtml
@model WordCategory
@{
    ViewData["Title"] = "Create";
}

<h2>Create Subjects</h2>
<div class="row">
    <div class="col-md-3">
        <form asp-action="Create" asp-controller="WordCategory" method="post">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="NameRu"></label>
                <input asp-for="NameRu" class="form-control" />
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
            <a asp-action="Index" class="btn btn-default">Cancel</a>
        </form>
    </div>
</div>

Translate/TranslateCore/Views/WordCategory/Edit.cshtml
@model WordCategory
@{
    ViewData["Title"] = "Edit";
}

<h2>Create Subjects</h2>
<div class="row">
    <div class="col-md-3">
        <form asp-action="Edit" asp-controller="WordCategory" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="NameRu"></label>
                <input asp-for="NameRu" class="form-control" />
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
            <a asp-action="Index" class="btn btn-default">Cancel</a>
        </form>
    </div>
</div>

Translate/TranslateCore/Views/WordCategory/Index.cshtml
@model IEnumerable<WordCategory>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col">
        <div class="caption">
            <h2>Word subjects</h2>
            <a class="btn btn-primary" asp-action="Create" asp-controller="WordCategory">Create word</a>
        </div>
        <div class="alphabet">
            @{
                char[] alphabet = Enumerable.Range('A', 26).Select(x => (char)x).ToArray();

                foreach (char symbol in alphabet)
                {
                    <a href="#" onclick="filterWord(event, 'WordCategory')">@symbol</a>
                }
            }
        </div>
        <table id="dictionary" class="table table-striped">
            <tr><th>Id</th><th>English</th><th>Russia</th><th></th></tr>
            @if (Model.Count() == 0)
            {
                <tr><td colspan="3" class="text-center">No words</td></tr>
            }
            else
            {
                @foreach (var wordCategory in Model)
                {
                    <tr>
                        <td>@wordCategory.Id</td>
                        <td>@wordCategory.Name</td>
                        <td>@wordCategory.NameRu</td>
                        <td>
                            <form asp-controller="WordCategory" asp-action="Delete" asp-route-id="@wordCategory.Id" method="post">
                                <a class="btn btn-sm btn-primary" asp-controller="WordCategory" asp-action="Edit" asp-route-id="@wordCategory.Id">Edit</a>
                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
</div>
<script src="~/js/translate.js"></script>